language: c
compiler:
  - gcc
#  - clang
before_install:
  - sudo apt-get -y install libgnutls-dev libgtk-3-dev libgtk2.0-dev libgcrypt20-dev libgpg-error-dev
  - ./admin/install-gwen.sh 223 4.99.25rc9
  - sudo apt-get -y install libgmp-dev libxmlsec1-dev
addons:
  apt:
    update: true
script:
  - ACLOCAL_FLAGS="-I /usr/share/aclocal" make -f Makefile.cvs
  - ./configure
  - make typedefs
  - make typefiles
  - make
  - make check
